"""fix recipient

Revision ID: 29454d65a925
Revises: f90b4d1b06a2
Create Date: 2024-09-29 14:59:14.481411

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "29454d65a925"
down_revision = "f90b4d1b06a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recipient_id", sa.Integer(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_message_recipient_id"), ["recipient_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_message_recipient_id", "user", ["recipient_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_message_recipient_id"))
        batch_op.drop_column("recipient_id")

    # ### end Alembic commands ###
